# Welcome to Jekyll!
# bundle exec jekyll serve --livereload
#
# YAML syntax
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# standard settings
title: schloschi 
email: schloschi23@gmail.com 
description: Digitales Notizbuch. Portfolio und Blog an der Schnittstelle von
Psychologie, Technologie und Outdoor.
url: "https://schloschi23.github.io"
baseurl: "" github_username:  schloschi23

# Build settings
theme: minima
plugins:
  - jekyll-feed

# browser settings
lang: de-DE
permalink: /:title/
date_format: "%d.%m.%Y"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

  ## --- Navigation ---
header_pages:
  - abenteuer/index.html
  - projekte/index.html
  - gedanken/index.html
