# Welcome to Jekyll!
# bundle exec jekyll serve --livereload
#
# YAML syntax
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# site
title: schloschi 
email: schloschi23@gmail.com 
description: >-
  Digitales Notizbuch und Portfolio mit Gedanken und Projekten an den
  Schnittstellen von Psychologie, Technologie und Outdoor.
url: "https://schloschi23.github.io"
baseurl: "" 
github_username: schloschi23

# build
theme: minima
  skin: dark
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.

sass:
  style: compressed
  quiet_deps: true


plugins:
  - jekyll-feed
  - jekyll-seo-tag  # Erstellt automatisch Meta-Tags f√ºr Google & Social Media
  - jekyll-sitemap  # Hilft Suchmaschinen, deine Struktur zu verstehen

# navigation
header_pages:
  - abenteuer/index.md
  - projekte/index.md
  - gedanken/index.md

# browser settings
lang: de-DE
permalink: /:title/
date_format: "%d.%m.%Y"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
